openapi: 3.0.0
info:
    title: mini_board
    description: daumtto53 first project
    version: 0.0.1
servers:
    - url: "localhost:5173"
paths:
    /board/{page}:
        get:
            summary: Returns a list of 10 items of board.
            parameters:
                - name: page
                  in: query
                  required: false
                  description: abc
                  schema:
                      type: integer
                      format: int64
                      minimum: 1
            responses:
              '200':
                description: A List of Board object.
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        id:
                          type: integer
                          format: int64
                          example: 4
                        title:
                          type: string
                        author:
                          type: string
                        date:
                          type: string
                          format: date
                        views:
                          type: integer
