openapi: 3.0.0
info:
    title: mini_board
    description: daumtto53 first project
    version: 0.0.1
servers:
    - url: "localhost:8080"
tags:
  - name: board
  - name: 댓글
paths:
    /board:
        get:
            tags:
              - board
            summary: 게시글 목록 조회
            description: 10개씩 조회
            parameters:
                - name: page
                  in: query
                  required: false
                  description: abc
                  schema:
                      type: integer
                      format: int64
                      minimum: 1
            responses:
                "200":
                    description: A List of Board object.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        format: int64
                                        example: 4
                                    title:
                                        type: string
                                    author:
                                        type: string
                                    regDate:
                                        type: string
                                        format: date
                                    views:
                                        type: integer
        post:
            summary: 게시글 등록
            tags:
              - board
            responses:
                "200":
                    description: A List of Board object.
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    id:
                                        type: integer
                                        format: int64
                                        example: 4
                                    title:
                                        type: string
                                    author:
                                        type: string
                                    regDate:
                                        type: string
                                        format: date
                                    views:
                                        type: integer

    /board/{postId}:
        get:
            summary: 게시글 조회
            description: ""
            tags:
              - board
            parameters:
                - name: postId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK
        put:
            summary: 게시글 수정
            tags:
              - board
            parameters:
                - name: postId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK
        delete:
            summary: 게시글 삭제
            tags:
              - board
            parameters:
                - name: postId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK

    /replies:
        get:
            summary: 댓글 목록 조회
            tags:
              - replies
            responses:
                "200":
                    description: OK
        post:
            summary: 댓글 등록
            tags:
              - replies
            responses:
                "200":
                    description: OK
    /replies/{replyId}:
        get:
            description: 댓글 조회
            tags:
              - replies
            parameters:
                - name: replyId
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK
        put:
            description: 댓글 수정
            tags:
              - replies
            parameters:
                - name: asdf
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK
        delete:
            description: 댓글 삭제
            tags:
              - replies
            parameters:
                - name: saf
                  in: path
                  required: true
                  schema:
                      type: integer
            responses:
                "200":
                    description: OK
